modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/Colytra/issues"
logoFile="colytra_icon.png"
[[mods]]
modId="colytra"
version="${version}"
displayName="Colytra"
displayURL="https://github.com/TheIllusiveC4/Colytra"
authors="C4"
description='''
Allows attachment of elytras to chestplates.
'''
[[dependencies.colytra]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.colytra]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.colytra]]
    modId="caelus"
    mandatory=true
    versionRange="${caelus_version_range}"
    ordering="NONE"
    side="BOTH"